data:
  - fuse_object: ""

    # io:
    #   input_key: None
    #   output_key: "dataset_pipeline"
  - object: "get_splits_str_ids"
    io:
      input_key: null
      output_key: "data_splits"

cache:
  num_workers: 1
  restart_cache: True
  root_dir: "path/to/cache"

mlflow:
  MLFLOW_TRACKING_URI: null
  MLFLOW_EXPERIMENT_NAME: null

modality_encoding_strategy:
  - object: "ModalityEncoding"


fusion_strategy:
  - object: "EncodedUnimodalToConcept"  # early or late
    args:
      use_autoencoders: True
      add_feature_names: False
      encoding_layers:
        - 32
        - &n_layers 16
      use_pretrained: True
      batch_size: 3
      training:
        model_dir: "model_concept"
        pl_trainer_num_epochs: 1
        pl_trainer_accelerator: "cpu"
      io:
        concept_encoder_model_key: "concept_encoder_model"
        output_key: "data.input.concatenated"
  - object: "ConceptToGraph"
    args:
      module_identifier: &graph_module "mplex"
      thresh_q: 0.95
      io:
        concept_encoder_model_key: "concept_encoder_model"
        fused_dataset_key: "fused_dataset"
        input_key: "data.input.concatenated"
        output_key: "data.derived_graph"

task_strategy:
  - object: "MultimodalGraphModel"
    args:
      io:
        fused_dataset_key: "fused_dataset"
        input_key: "data.derived_graph"
        target_key: &target "data.gt.gt_global.task_1_label"
        prediction_key: &prediction "model.out"


      model_config:
        graph_model:
          module_identifier: *graph_module
          n_layers: *n_layers
          node_emb_dim: 1  # really needed?
        head_model:
          head_hidden_size:
            - 100
            - 20
          dropout: 0.5
          add_softmax: True
        num_classes: 2

      training:
        model_dir: "model_mplex"
        batch_size: 3
        best_epoch_source:
          mode: "max"
          monitor: "validation.metrics.auc"
        train_metrics:
          key: "auc"
          object: "MetricAUCROC"
          args:
            pred: *prediction
            target: *target
        validation_metrics:
          key: "auc"
          object: "MetricAUCROC"
          args:
            pred: *prediction
            target: *target
        pl_trainer_num_epochs: 1
        pl_trainer_accelerator: "cpu"
        pl_trainer_devices: 1

      testing:
        test_results_filename: &test_results_filename "test_results.pickle"
        evaluation_directory: &evaluation_directory "eval"

  - object: "Eval"
    args:
      test_results_filename: *test_results_filename
      evaluation_directory: *evaluation_directory
